language: node_js
node_js:
  - 4.0
before_install:
  - npm install -g grunt-cli
install:
  - npm install
script:
  # Reference the locally-installed version of Grunt
  - ./node_modules/grunt-cli/bin/grunt test

notifications:
  email: false

deploy:
  # Deploy master to staging (govuk-elements-test.herokuapp.com)
  - provider: heroku
    api_key:
        secure: MSMzniJpxcjP1jbsjqaAR/bU/FtGRrYYrrIekzaXNXtUiwNOsnd2MMMiBiuwzRaqHlEZzUkh70jyCuAoztnMzr5vAlwy9IW5BnGhacbDZsyFZ8AS1Z0Glq0l7q0nh1akCEVYhdGyABrc2NMaAqtaVovEbAfZYCrSX8Uu0CRbPfY=
    app: govuk-elements-test
    on: master
  # Deploy tagged build to production (govuk-elements.herokuapp.com)
  - provider: heroku
    api_key:
        secure: MSMzniJpxcjP1jbsjqaAR/bU/FtGRrYYrrIekzaXNXtUiwNOsnd2MMMiBiuwzRaqHlEZzUkh70jyCuAoztnMzr5vAlwy9IW5BnGhacbDZsyFZ8AS1Z0Glq0l7q0nh1akCEVYhdGyABrc2NMaAqtaVovEbAfZYCrSX8Uu0CRbPfY=
    app: govuk-elements
    on:
      all_branches: true
      tags: true

sudo: false
